notifications:
  email: false

language: c
dist: bionic
osx_image: xcode10.1

branches:
  only:
  - master

compiler:
  - gcc
  - clang
os:
  - if [ $TRAVIS_CPU_ARCH = ppc64le ]; then linux; else linux; osx; fi

matrix:
  exclude:
    - os: osx
      compiler: gcc

addons:
  apt:
    packages:
    - freeglut3
    - freeglut3-dev
    - libglew1.5
    - libglew1.5-dev
    - libglu1-mesa
    - libglu1-mesa-dev
    - libgl1-mesa-glx
    - libgl1-mesa-dev
    - libpulse-dev
    - libalut-dev

before_script:
  - mkdir release && cd release

script:
  - cmake ..
  - make
